Repository cassiofb-dev/textgrader, pull requests merged in 2023-04, with the labels that each got.

#20 Feature/19 predict grades from essays
  README.md
  backend/src/README.md
  backend/src/api.py
  backend/src/dags/config.py
  backend/src/dags/escondo/general.py
  backend/src/dags/escondo/runner.py
  backend/src/dags/escondo/simple.py
  backend/src/dags/experiments/experiments.py
  backend/src/dags/experiments/feature_engineering.py
  backend/src/dags/feature_engineering/generate_features.py
  backend/src/dags/feature_engineering/latent_semantic_indexing.py
  backend/src/dags/feature_engineering/word_embeddings.py
  backend/src/dags/general_tasks.py
  backend/src/dags/logging.py
  backend/src/dags/model_training/doc_to_vec_trainer.py
  backend/src/dags/model_training/train_model.py
  backend/src/dags/predict/predict.py
  backend/src/dags/predict/predict_from_text.py
  backend/src/dags/preprocessing/general_preprocessing.py
  backend/src/dags/preprocessing/spell_correct.py
  backend/src/dags/preprocessing/word_features.py
  backend/src/dags/run.py
  backend/src/dags/runner.py
  backend/src/dags/utils.py
  backend/src/run.py
  docker-compose.yml
Labels: documentation, enhancement

#22 Feature/21 create and train models on docker compose startup
  backend/requirements.txt
  backend/src/dags/experiments/experiments.py
  backend/src/requirements.py
  docker-compose.yml
Labels: enhancement

#23 Enhance UI
  docker-compose.yml
  frontend/package-lock.json
  frontend/src/pages/_app.tsx
  frontend/src/pages/about.tsx
  frontend/src/pages/index.tsx
  frontend/src/pages/redacao.tsx
  frontend/yarn.lock
Labels: enhancement

#25 Feature/24 textgrader mvp
  backend/src/dags/predict/predict_from_text.py
  frontend/src/pages/_app.tsx
  frontend/src/pages/redacao.tsx
  frontend/src/pages/sobre.tsx
Labels: bug, enhancement

#30 feat: add support for pt-br
  backend/src/dags/feature_engineering/word_embeddings.py
  docker-compose.yml
Labels: enhancement

#32 Release/v0.1.1
  backend/src/dags/feature_engineering/word_embeddings.py
  docker-compose.yml
Labels: Release
